### PR TITLE
fix issue 17

### LINKED ISSUE #17: Fresh context data deserialization failure
Building on #14 ... the serialized data on disk looks far better. However, deserialization doesn't seem to be working correctly if attempted from a fresh process. Let me explain further with some code:

```
            needle = data_list[-1]

            assert needle in iocs
            print(f"[PASS] assert {needle} in data_list")

            assert xorf.contains(needle)
            print(f"[PASS] assert xorf.contains({needle})")

            with open(local_path, "wb+") as fh:
                fh.write(xorf_data)

            with open(local_path, "rb") as fh:
                deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())

            assert deserialized_xor.contains(needle)
            print(f"[PASS] assert deserialized_xor.contains({needle})")

            del(deserialized_xor)
```

The above code passes all assertions without fail. However, try this from another process:

```
            with open(local_path, "rb") as fh:
                deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())
            assert deserialized_xor.contains("EXPECTED VALUE")
```

This will fail.  None of the expected values are found in the deserialized xorfilter from a fresh context.

### PR DESCRIPTION
**Pull request by lemire**
Issue 17 raised by @pedramamini shows that serialization and deserialization only work while remaining in the same Python process. That is because [pyxorfilter](https://github.com/glitzflitz/pyxorfilter) relies on the default Python hash function which is *randomized*. This PR fixes this issue by adopting xxhash which relies on a fixed seed.

fixes: https://github.com/glitzflitz/pyxorfilter/issues/17

### CODE REVIEW

**Comment by lemire** [comment]
@glitzflitz I think that this could be merged and released.

**Comment by lemire** [comment]
@glitzflitz Ping!

**Comment by vshuraeff** [comment]
still waiting

**Comment by lemire** [comment]
@glitzflitz  Ping !

**Comment by glitzflitz** [comment]
Sorry for delay but LGTM. Merged!

**Pull request merged**
